version: '2' 
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
    environment:
      - NAMENODE_HOSTNAME=namenode
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"

  spark-submit:
    build: ./pyspark
    image: spark-submit
    container_name: spark-submit
    env_file:
      - ./hadoop.env
    environment:
      - SPARK_HOME=/spark
    depends_on:
      - datanode
      - namenode
      - spark-worker-1
      - spark-worker-2
      - spark-master

  hdfscli:
    build: ./hdfscli
    image: hdfscli
    container_name: hdfscli
    env_file:
      - ./hadoop.env
    volumes:
      - ./hdfs-data:/opt/data
    depends_on:
      - datanode
      - namenode

  spark-worker-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - NAMENODE_HOSTNAME=namenode
      - "constraint:node==spark-worker-1"
    env_file:
      - ./hadoop.env


  spark-worker-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - NAMENODE_HOSTNAME=namenode
      - "constraint:node==spark-worker-2"
    env_file:
      - ./hadoop.env
